import { defineConfig } from 'vitest/config';

// TZ is pinned to UTC for the same reason the timing app pins it: the suite would
// otherwise pass or fail depending on the machine's own timezone, and Nightingale
// Nightmare sits the weekend after the clocks change. See docs/architecture/principles.md.
process.env.TZ = 'UTC';

export default defineConfig({
  test: {
    projects: [
      {
        test: {
          name: 'unit',
          include: [
            'packages/*/tests/unit/**/*.test.ts',
            'apps/*/tests/unit/**/*.test.ts',
          ],
          environment: 'node',
        },
      },
      {
        test: {
          name: 'db',
          // Needs the local Supabase stack: `npm run db:start`.
          include: ['packages/db/tests/**/*.test.ts'],
          environment: 'node',
        },
      },
    ],

    // ---------------------------------------------------------------------------------
    // Coverage, and what it is and is not allowed to mean here.
    // ---------------------------------------------------------------------------------
    //
    // **This measures the unit layer only, and `include` says so.** Four layers test this
    // platform and each tests something the layer below cannot — unit, database against a
    // real Postgres, the Workers runtime via Miniflare, and Playwright with axe. Three of
    // those four run in a separate process from this one: the database tests reach Postgres
    // over the wire, the Worker tests run inside `workerd`, and Playwright drives a browser.
    // None of them can be instrumented by this provider, so a number produced here is
    // **the share of pure logic reached by pure tests** and nothing wider.
    //
    // That distinction is the whole reason `include` is a list rather than `src/**`. A file
    // that is deliberately proven at another layer — the Worker entrypoint, the request
    // handlers, the Astro pages — would otherwise sit at 0% and drag the number down, and
    // the only way to move it would be to write a worse test at the wrong layer. Excluding
    // it is not hiding it; it is declining to publish a figure that would be read as a gap
    // when it is a deliberate choice. What is in this list is code that a unit test is the
    // *right* tool for, which is what makes a threshold on it honest.
    //
    // The exclusions each say why below. Add to `include` when a module becomes pure enough
    // to be worth unit testing, rather than lowering the thresholds to fit it.
    coverage: {
      provider: 'v8',
      // Files never imported by a test still count. Without this the number reports the
      // coverage of the code that happens to be tested, which is always near 100% and
      // always meaningless — a module with no test at all simply disappears from it.
      all: true,
      include: [
        'packages/shared/src/**/*.ts',
        'apps/main/worker/**/*.ts',
        'packages/db/src/**/*.ts',
      ],
      exclude: [
        // Generated by `supabase gen types`. `db:types:check` is what guards it, and it is
        // a type declaration with no runtime behaviour to cover.
        'packages/db/src/database.types.ts',
        // Re-export barrels. Covering them measures the `export` keyword.
        '**/index.ts',
        // Everything below is proven at a layer this provider cannot see, and each is
        // listed one by one so that adding to this list is a decision somebody takes in a
        // diff rather than a glob quietly widening.
        //
        // The Worker's request surface — tests/worker/** drives it inside workerd, and
        // apps/main/tests/e2e/** drives it through a browser.
        'apps/main/worker/index.ts',
        'apps/main/worker/nn-admin.ts',
        'apps/main/worker/nn-entry.ts',
        'apps/main/worker/nn-entry-complete.ts',
        'apps/main/worker/nn-signup.ts',
        'apps/main/worker/stripe-webhook.ts',
        'apps/main/worker/medical-retention.ts',
        // The Supabase client factory and the two health round trips. Each is a thin
        // wrapper whose only meaningful assertion is that it reaches a real Postgres —
        // packages/db's tests and the smoke test — rather than a mock of the client here.
        // `health-report.ts` is deliberately *not* in this list: `healthResponse()` decides
        // 200 against 503 and that decision is pure, so it belongs in the number.
        'packages/shared/src/supabase.ts',
        'packages/shared/src/health.ts',
        'packages/shared/src/ping.ts',
      ],
      reporter: ['text', 'html', 'lcov'],
      reportsDirectory: './coverage',
      // **A ratchet, not an aspiration, and it is deliberately set low.** These are what
      // the suite reaches today, rounded down by a point. A threshold above what is
      // actually reached is a red pipeline on the day it lands, which teaches everybody to
      // lower it; a threshold at today's floor fails only on a real regression, which is
      // the one thing a number like this is good for.
      //
      // **It is low because `admin.ts` is at 12%**, and that is a finding rather than a
      // baseline to be comfortable with — see docs/delivery/test-coverage.md. Raise these
      // as each module lands. Never lower one to make a red run green: a fall means a
      // module lost its tests, which is exactly what this is here to notice.
      thresholds: {
        lines: 66,
        functions: 70,
        branches: 58,
        statements: 66,
      },
    },
  },
});
