/**
 * The Worker's real entrypoint — `wrangler.jsonc`'s `main`.
 *
 * ## Why this file exists at all, when `.open-next/worker.js` was the entrypoint for a year
 *
 * A Durable Object class has to be **exported from the Worker's entry module** for Wrangler to
 * bind it. `.open-next/worker.js` is generated by `opennextjs-cloudflare build` from a template
 * inside the package — it is not ours to edit, it is `.gitignore`d, and it is rewritten on every
 * build. So the entry becomes a file we own that re-exports everything OpenNext's does, plus the
 * one class that is ours.
 *
 * ⚠️ **This is the answer to the viability question
 * [#204](https://github.com/southville-running-club/src-website/issues/204) was told to settle
 * before building anything**, and it is worth writing down because the obvious readings are both
 * wrong: OpenNext has no configuration hook for a custom Durable Object, and `.open-next/` is not
 * a directory to patch. What it does have is an ordinary ES module as its output, and a Worker's
 * entry is whatever `main` points at.
 *
 * ## ⚠️ Plain JavaScript, on purpose
 *
 * `.open-next/worker.js` does not exist until the build has run, and `tsc` would refuse to
 * resolve it in CI — which lint-and-typechecks a fresh checkout *before* it builds. It also
 * carries its own `@ts-expect-error` imports of files that only Wrangler's bundler resolves. A
 * `.ts` entry would have to suppress an error that is sometimes present and sometimes not, which
 * is the one thing `@ts-expect-error` cannot do.
 *
 * So the entry is `.js`, holds no logic of its own, and everything it needs lives in
 * `worker/leaderboard-socket.ts` and `durable-objects/leaderboard-room.ts` — both typechecked,
 * against the Workers runtime, by `worker/tsconfig.json`. `apps/timing/public/sw.js` is the other
 * hand-written JavaScript in this application and the precedent for declaring its globals in
 * `eslint.config.js`; this file needs none, because it touches no global.
 *
 * ## The three re-exports, and why none of them may be dropped
 *
 * OpenNext's template exports `DOQueueHandler`, `DOShardedTagCache` and `BucketCachePurge`
 * unconditionally — they are the classes its own cache and revalidation overrides bind when a
 * project configures them. None is bound in `wrangler.jsonc` today, and re-exporting an unbound
 * class costs nothing. **Dropping them would cost the day somebody configures an incremental
 * cache** and finds the binding refused by a Worker whose entry no longer exports the class, with
 * nothing pointing here.
 *
 * ## What it must not become
 *
 * ⚠️ **Nothing that can answer a page belongs in this file.** Every request that is not the
 * leaderboard socket goes to OpenNext untouched, which is what keeps `middleware.ts` the one door
 * for every address under `/timing` — [ADR-037](../../../docs/architecture/decisions/adr-037-timing-stays-on-next-under-opennext.md)
 * and [#243](https://github.com/southville-running-club/src-website/issues/243). The socket is
 * here because a `101` response cannot survive Next's response pipeline at all;
 * `worker/leaderboard-socket.ts`'s header carries that argument and the three properties that
 * keep its own permission check honest.
 */

import openNextWorker from './.open-next/worker.js';
import { handleLeaderboardSocket } from './worker/leaderboard-socket';

export {
  DOQueueHandler,
  DOShardedTagCache,
  BucketCachePurge,
} from './.open-next/worker.js';

export { LeaderboardRoom } from './durable-objects/leaderboard-room';

export default {
  /**
   * @param {Request} request
   * @param {CloudflareEnv} env
   * @param {ExecutionContext} ctx
   */
  async fetch(request, env, ctx) {
    // `null` means "not the socket", which is every other request this Worker serves. The check
    // is two header reads and at most one `URL` parse — see that module's header.
    const socket = await handleLeaderboardSocket(request, env);

    return socket ?? openNextWorker.fetch(request, env, ctx);
  },
};
