import { getCloudflareContext } from '@opennextjs/cloudflare';
import { cookies } from 'next/headers';
import type { Database } from '@src/db';
import { createUserClient, type SupabaseConfig } from '@src/shared';
import { ACCESS_COOKIE } from '@src/shared/session-cookies';

/**
 * The functions `timing` actually grants, straight off the generated types.
 *
 * ⚠️ **Worth the extra line rather than `fn: string`.** The first version of this file took a
 * bare string and the build caught it: with the union, a typo or a function nobody granted is
 * a compile error, and `packages/db/tests/timing.test.ts`'s pinned grant list and this type
 * are then two independent statements of the same set. `database.types.ts` is regenerated by
 * `npm run db:types`, so adding a function here costs nothing and removing one breaks the
 * caller rather than the runtime.
 */
export type TimingFunction = keyof Database['timing']['Functions'];

/**
 * Reading the `timing` schema as the signed-in person, from a server component.
 *
 * ## Three answers, not two — and conflating any pair of them is a bug with a cost
 *
 * Every read in `timing` returns `null` for **both** "you may not" and "no such event",
 * deliberately, so a slug cannot be probed for existence. That leaves a page with three
 * distinct outcomes and only two obvious ones:
 *
 * | | What the page must say |
 * | --- | --- |
 * | A row came back | the row |
 * | `null` | *"Not found"* — the refusal and the missing event, indistinguishable |
 * | The call **failed** | that the database could not be reached |
 *
 * ⚠️ **The third must never render as the second.** A page that says "Not found" during an
 * outage tells a volunteer the race they set up has been deleted, on the morning they are
 * setting up a start line. `apps/main` learned the mirror image of this on `/events/`:
 * `fetchSocialState` distinguishes `missing` from `unavailable` because *"a page that 404'd on
 * an unreachable database would delete itself for the length of the outage"*. Same rule,
 * pointing the other way.
 *
 * So {@link readTiming} returns a discriminated union and the caller has to handle all three.
 */
export type TimingRead<T> =
  { state: 'ok'; data: T } | { state: 'none' } | { state: 'unavailable' };

/**
 * Where the two Supabase variables come from, which is **not the same place in every
 * environment**. Deployed, OpenNext puts the Worker's `vars` into `process.env`; under
 * `next dev` it does not, and `getCloudflareContext()` is the bridge. Copied from
 * `app/health/route.ts`, which carries the full reasoning — and deliberately the **async**
 * form, not `middleware.ts`'s synchronous one.
 */
export async function config(): Promise<SupabaseConfig> {
  try {
    const { env } = await getCloudflareContext({ async: true });
    return {
      url: env.PUBLIC_SUPABASE_URL ?? process.env.PUBLIC_SUPABASE_URL ?? '',
      anonKey: env.PUBLIC_SUPABASE_ANON_KEY ?? process.env.PUBLIC_SUPABASE_ANON_KEY ?? '',
    };
  } catch {
    return {
      url: process.env.PUBLIC_SUPABASE_URL ?? '',
      anonKey: process.env.PUBLIC_SUPABASE_ANON_KEY ?? '',
    };
  }
}

/**
 * Call one `timing` function as the person whose cookie this request carries.
 *
 * ⚠️ **`.schema('timing')` is not optional.** `createUserClient` pins `db.schema` to
 * `identity` — that is what lets `middleware.ts` write a bare `.rpc('my_permissions')` — so a
 * bare `.rpc('list_events')` here would look for `identity.list_events` and fail in a way that
 * reads as a missing function. `packages/shared/src/supabase.ts` documents the whole class of
 * bug.
 *
 * **No service key, ever.** The call carries the person's own access token, so
 * `identity.has_permission()` inside each function resolves against `auth.uid()` and every
 * refusal is the database's rather than this file's. If a read here ever seems to need a
 * service key, the policy is wrong and that is the thing to fix.
 */
export async function readTiming<T>(
  fn: TimingFunction,
  args: Record<string, unknown> = {},
): Promise<TimingRead<T>> {
  const accessToken = (await cookies()).get(ACCESS_COOKIE)?.value;

  if (!accessToken) {
    // The middleware refuses a request with no token long before this runs, so reaching here
    // means the cookie went missing between the gate and the render. Not an outage.
    return { state: 'none' };
  }

  try {
    const asPerson = createUserClient(await config(), accessToken);
    // The argument object is cast because `fn` is a union and `rpc` narrows its `args` type
    // per function; the **name** is what is checked, which is the half that catches a typo.
    const { data, error } = await asPerson.schema('timing').rpc(fn, args as never);

    if (error) {
      // A code and a message, never a row — the discipline `apps/main/worker/admin.ts` keeps,
      // because a log line is somewhere a volunteer's data must not end up.
      console.error(`timing: ${fn} unavailable — ${error.code}: ${error.message}`);
      return { state: 'unavailable' };
    }

    return data === null ? { state: 'none' } : { state: 'ok', data: data as T };
  } catch (cause) {
    console.error(
      `timing: ${fn} threw — ${cause instanceof Error ? cause.message : cause}`,
    );
    return { state: 'unavailable' };
  }
}
